[package]
name = "pulsar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = [ "lib" ]

# [workspace]
# members = [ "crates/*" ]

[dependencies]
ahash = "0.8.3"
# hex = "0.4.3"
# tokio = { version = "1.25.0", features = [ "full" ] }

[dev-dependencies]
criterion = "0.4.0"

[profile.bench]
opt-level = 3
strip = true
lto = true
codegen-units = 1
debug-assertions = false
overflow-checks = true
panic = "abort"

[[bench]]
name = "world"
harness = false
