[package]
name = "pulsar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = [ "lib" ]

[features]
default = [ ]

[dependencies]
ahash = "*"
tower = "*"

[dev-dependencies]
criterion = "0.4.0"

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
