[package]
name = "pulsar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = [ "rlib" ]

[workspace]
members = [ "crates/*" ]

[dependencies]
tokio = { version = "1.25.0", features = [ "full" ]}

[dev-dependencies]
criterion = "*"
rand = "*"

[[bench]]
name = "main"
harness = false