[package]
name = "pulsar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = [ "lib" ]

[workspace]
members = [ "crates/*" ]

[features]
default = [ "prost", "ecs", "instancing" ]
prost = [ "dep:prost" ]
ecs = [ "dep:ahash" ]
instancing = [ "dep:pulsar-instancing" ]

[dependencies]
ahash = { version = "0.8.3", optional = true }
prost = { version = "0.11.6", optional = true }
pulsar-instancing = { path = "crates/pulsar-instancing", optional = true }
tokio = { version = "1.25.0", features = [ "full" ] }
tower = "*"

[dev-dependencies]
criterion = "0.4.0"

[profile.release]
opt-level = 3
strip = true
lto = true
codegen-units = 1
